# Hand-maintained type stubs. Update by hand when bindings change.
from __future__ import annotations
from numpy.typing import ArrayLike

INF_WEIGHT: int

class ContractionHierarchy:
    @staticmethod
    def build(
        n_nodes: int,
        tail: ArrayLike,
        head: ArrayLike,
        weight: ArrayLike,
        max_pop_count: int = 500,
    ) -> ContractionHierarchy: ...
    def save(self, path: str) -> None:
        """Write to RoutingKit native binary file (loadable by any RoutingKit application)."""
        ...
    def save_file(self, path: str) -> None:
        """Write to RoutingKit native binary file (matches RoutingKit C++ API name)."""
        ...
    @staticmethod
    def load(path: str) -> ContractionHierarchy:
        """Load from RoutingKit native binary file."""
        ...
    @staticmethod
    def load_file(path: str) -> ContractionHierarchy:
        """Load from RoutingKit native binary file (matches RoutingKit C++ API name)."""
        ...
    @property
    def node_count(self) -> int: ...

class CHQuery:
    def __init__(self, ch: ContractionHierarchy) -> None: ...
    def reset(self) -> CHQuery: ...
    def add_source(self, node: int) -> CHQuery: ...
    def add_target(self, node: int) -> CHQuery: ...
    def run(self) -> CHQuery: ...
    def get_distance(self) -> int: ...
    def get_node_path(self) -> list[int]: ...
    def get_arc_path(self) -> list[int]: ...
